### ISSUE TITLE
Bug/Regression: Inability to filter by facet with `one_dashboard_raw`

### ISSUE THREAD

**Issue by rdhar** [newrelic/terraform-provider-newrelic#1413]
### Summary

The newly-introduced `one_dashboard_raw` ([documentation](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/one_dashboard_raw)) does not appear to support filtering by facets, which is a significant regression.

### Expected Behaviour

Much like `one_dashboard`, it should be possible to filter by facet using the `linked_entity_guids` attribute, or similar alternative.

### Actual Behaviour

There is no replacement or workaround. If anything, now the account ID needs to be explicitly declared which is undoes the work done in #1193 merged in #1219 for v2.19.0 to inherit the dashboard's account ID by default.

### Environment

* Terraform: v1.0.3
* Provider: v2.24.1
* OS: Windows 10 Pro

Thanks for your time.

**Comment by rdhar** [comment]
I can understand marking this as stale due to the lack of activity. That being said, this is a significant regression of functionality preventing wider adoption of `one_dashboard_raw` in most capacities. Would hope this considered as a priority for complete configuration of dashboard, per #1211.

**Comment by rdhar** [comment]
Hi @kidk. Per #1211, bumping this as the lack of facet filtering is a significant regression blocking wider adoption of `one_dashboard_raw`.

**Comment by rdhar** [comment]
Following the release of [v2.30.0](https://github.com/newrelic/terraform-provider-newrelic/releases/tag/v2.30.0), the [changelog](https://github.com/newrelic/terraform-provider-newrelic/blob/v2.30.0/CHANGELOG.md) mentions the introduction of `filter_current_dashboard` feature to determine the linked page entity guid automatically. This is great news, many thanks for the implementation @pmillett! Would it be possible to share some documentation around usage example please, @jthurman42?

There are at least three issues (#1349, #1200, #1193) which are perfectly resolved by this feature. Could you also confirm this applies to `one_dashboard_raw` just as it does to `one_dashboard` for a consistent roll-out?

**Comment by rgembalik** [comment]
Unfortunately, using `filter_current_dashboard = true` is still not possible in `one_dashboard_raw` and using data source to query entity for `linked_entity_guids` is not an option when the name of a dashboard can change. I would love to see this improvement added as it would solve a lot of issues with our dashboards.

**Comment by NSSPKrishna** [comment]
Hello everyone, we have released a possible fix in the latest version. Please notify us if the issue still persist.
